### ISSUE TITLE
Unhandled 'error' event

### ISSUE THREAD

**Issue by heroboy** [dex4er/js-promise-socket#1] opened 2017-11-03 05:37 UTC
```
events.js:182
      throw er; // Unhandled 'error' event
      ^

Error: read ECONNRESET
    at _errnoException (util.js:1019:11)
    at TCP.onread (net.js:608:25)
```
my code:
https://gist.github.com/heroboy/c9a793b15f95afc190ba035e91181276
```javascript
async function queryDns(buf)
{
	var sock = new PromiseSocket();
	await sock.connect({ host: '8.8.8.8', port: 53 });
	var sizeBuffer = Buffer.allocUnsafe(2);
	sizeBuffer.writeUInt16BE(buf.length);
	sock.write(sizeBuffer);
	sock.write(buf);

	sizeBuffer = await sock.read(2);
	var ret = await sock.read(sizeBuffer.readUInt16BE(0));
	sock.end();
	return ret;
}
```

**Comment by heroboy** [comment] 2017-11-19 08:23
I guess, do I need to `await socket.write`?

**Comment by dex4er** [comment] 2018-01-25 17:13
Sorry, I missed this issue, but yes: it is promisified version of streams and you can check `examples/simple-http-client.js` for analogy: `sock.write` is async method so `await` should be used instead.

`read` and `write` waits for `error` event too: then promise just rejects.

**Comment by heroboy** [comment] 2018-01-26 01:36
@dex4er I had tried `await socket.write`, not works. And you can see the stack `at TCP.onread (net.js:608:25)`, the exception was thrown when it was reading not writing.

**Comment by heroboy** [comment] 2018-01-26 01:53
Please try:
```javascript
const { PromiseSocket } = require('promise-socket')
const packet = require('dns-packet');
const dgram = require('dgram')
async function queryDns(buf)
{
	var sock = new PromiseSocket();
	await sock.connect({ host: '8.8.8.8', port: 53 });
	var sizeBuffer = Buffer.allocUnsafe(2);
	sizeBuffer.writeUInt16BE(buf.length);
	await sock.write(sizeBuffer);
	await sock.write(buf);

	sizeBuffer = await sock.read(2);
	var ret = await sock.read(sizeBuffer.readUInt16BE(0));
	sock.end();
	console.log('end')
	return ret;
}

var buf = packet.encode({
	type: 'query',
	id: 1,
	flags: packet.RECURSION_DESIRED,
	questions: [{
		type: 'A',
		class: 'IN',
		name: 'baidu.com'
	}]
})

setInterval(()=>{

	try
	{
		queryDns(buf);
	}
	catch (e)
	{
	
	}
},70);
```
Within 1 or 2 minutes, it will 
```
events.js:136
      throw er; // Unhandled 'error' event
      ^

Error: read ECONNRESET
    at _errnoException (util.js:999:13)
    at TCP.onread (net.js:629:25)```

**Comment by heroboy** [comment] 2018-01-26 02:07
Please try:
```
const { PromiseSocket } = require('promise-socket')
const packet = require('dns-packet');
const dgram = require('dgram')
async function queryDns(buf)
{
	var sock = new PromiseSocket();
	await sock.connect({ host: '8.8.8.8', port: 53 });
	var sizeBuffer = Buffer.allocUnsafe(2);
	sizeBuffer.writeUInt16BE(buf.length);
	await sock.write(sizeBuffer);
	await sock.write(buf);

	sizeBuffer = await sock.read(2);
	var ret = await sock.read(sizeBuffer.readUInt16BE(0));
	sock.end();
	console.log('end')
	return ret;
}

var buf = packet.encode({
	type: 'query',
	id: 1,
	flags: packet.RECURSION_DESIRED,
	questions: [{
		type: 'A',
		class: 'IN',
		name: 'baidu.com'
	}]
})

setInterval(() =>
{
	queryDns(buf).then(()=>{},()=>{});
}, 70);

```
Within some minutes, it will give you
```
events.js:136
      throw er; // Unhandled 'error' event
      ^

Error: read ECONNRESET
    at _errnoException (util.js:999:13)
    at TCP.onread (net.js:629:25)
```

**Comment by dex4er** [comment] 2018-01-30 18:04
I can't reproduce this problem (i don't get this exception) but I believe it might be some race that I could fix it with extra `socket.on('error')` before any `read`.

BTW, `end()` method is async too, so you should do `await sock.end()`.

**Comment by dex4er** [comment] 2018-02-05 01:39
Hi @heroboy again. Can you test with latest promise-socket@3.0.0 ?

Thanks!

**Comment by heroboy** [comment] 2018-02-05 04:36
@dex4er Even the origin version, it is very hard to reproduce the problem. I tried the new version, for now it didn't crash.

**Comment by dex4er** [comment] 2018-02-05 09:36
Ok, I'm closing this bug report. And thanks for your time!

**Closed by dex4er** 2018-02-05 09:36 UTC
